name: Build FFmpeg Android

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86, riscv64, armv7, x86_64]
        ffmpeg_static: [false, true]
      fail-fast: false
    env:
      BUILD_DIR: ${{ github.workspace }}/build
      LATEST_GIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies and build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential jq cmake ninja-build make autoconf automake libtool pkg-config texinfo gettext gperf bison flex git xz-utils unzip diffutils file findutils coreutils binutils python3 python3-pip python3-venv pipx subversion libtool-bin nasm yasm

      - name: Install pipx and meson
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
          export PATH="$HOME/.local/bin:$PATH"
          pipx install meson
          meson --version

      - name: Install Android NDK (r29 beta4)
        run: |
          cd $HOME
          curl -LO https://dl.google.com/android/repository/android-ndk-r29-beta4-linux.zip
          unzip android-ndk-r29-beta4-linux.zip
          mv android-ndk-r29-beta4 $HOME/android-ndk-r29

          echo "ANDROID_NDK_ROOT=$HOME/android-ndk-r29" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-ndk-r29" >> $GITHUB_ENV

          TOOLCHAIN=$HOME/android-ndk-r29/toolchains/llvm/prebuilt/linux-x86_64/bin
          ln -sf $TOOLCHAIN/aarch64-linux-android21-clang    $TOOLCHAIN/aarch64-linux-android-gcc
          ln -sf $TOOLCHAIN/armv7a-linux-androideabi21-clang $TOOLCHAIN/arm-linux-androideabi-gcc
          ln -sf $TOOLCHAIN/x86_64-linux-android21-clang     $TOOLCHAIN/x86_64-linux-android-gcc
          ln -sf $TOOLCHAIN/i686-linux-android21-clang       $TOOLCHAIN/i686-linux-android-gcc

          echo "$TOOLCHAIN" >> $GITHUB_PATH

      - name: Set ARCH and FFMPEG_STATIC
        run: |
          echo "ARCH=${{ matrix.arch }}" >> $GITHUB_ENV
          echo "BUILD_TARGET=android" >> $GITHUB_ENV
          if [ "${{ matrix.ffmpeg_static }}" == "true" ]; then
            echo "FFMPEG_STATIC=1" >> $GITHUB_ENV

      - name: Build FFmpeg
        run: |
          rm -f git-sources.lock
          bash ${{ github.workspace }}/build.sh
        env:
          ARCH: ${{ matrix.arch }}
          LATEST_GIT: 1

      - name: Upload module files (zip and deb) to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: module-files-${{ matrix.arch }}-${{ matrix.ffmpeg_static }}
          path: |
            ${{ github.workspace }}/module/*.zip
            ${{ github.workspace }}/module/*.deb

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract FFmpeg commit
        id: ffmpeg
        run: |
          ZIP_FILE=$(find artifacts -name "*-Static-android-arm64-v8a.zip" | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "Error: Could not find aarch64 Static build zip"
            exit 1
          fi
          FFMPEG_COMMIT=$(unzip -p "$ZIP_FILE" ffmpeg_commit.txt)
          echo "FFMPEG_COMMIT=$FFMPEG_COMMIT" >> $GITHUB_ENV

      - name: Show collected files
        run: ls -R artifacts

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_ENV  

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "FFmpeg Android Build ${{ github.run_number }}"
          body: |
            ## FFmpeg Android Build ${{ github.run_number }}

            **Build Date:** ${{ env.BUILD_DATE }}  
            **Repo Commit:** [View Commit](https://github.com/FFmpeg/FFmpeg/commit/${{ env.FFMPEG_COMMIT }})  
            **Artifacts:** [Download Release](https://github.com/${{ github.repository }}/releases/tag/build-${{ github.run_number }})
          files: |
            artifacts/**/*.zip
            artifacts/**/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send build info to Telegram
        if: success()
        run: |
          python3 << 'EOF'
          import os
          import requests

          TELEGRAM_TOKEN = os.environ['TELEGRAM_TOKEN']
          CHANNEL_ID = "@ffmpegandroid"

          def send_message(text):
              url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
              data = {
                  'chat_id': CHANNEL_ID,
                  'text': text,
                  'parse_mode': 'Markdown'
              }
              response = requests.post(url, data=data)
              return response.json()

          announcement = f"""🚀 **FFmpeg Android Build {os.environ['GITHUB_RUN_NUMBER']}**

          📅 **Build Date:** {os.environ['BUILD_DATE']}
          🔗 **Repo Commit:** [View Commit](https://github.com/FFmpeg/FFmpeg/commit/{os.environ['FFMPEG_COMMIT']})
          📦 **Release:** [Download](https://github.com/{os.environ['GITHUB_REPOSITORY']}/releases/tag/build-{os.environ['GITHUB_RUN_NUMBER']})"""

          result = send_message(announcement)
          if result.get('ok'):
              print("✅ Announcement sent successfully")
          else:
              print(f"❌ Failed to send announcement: {result.get('description', 'Unknown error')}")
          EOF
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          BUILD_DATE: ${{ env.BUILD_DATE }}
          FFMPEG_COMMIT: ${{ env.FFMPEG_COMMIT }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  update-jsons:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract changelog.md
        run: |
          ZIP_FILE=$(find artifacts -name "*-Static-android-arm64-v8a.zip" | head -n 1)
          unzip -p "$ZIP_FILE" changelog.md > changelog.md

      - name: Update all JSON files
        run: |
          ARCHS="aarch64 x86 riscv64 armv7 x86_64"
          TYPES="Dynamic Static"

          cd artifacts

          for ARCH in $ARCHS; do
            for TYPE in $TYPES; do
              ZIP_FILE=$(find . -name "*.zip" | grep -i "$ARCH" | grep -i "$TYPE" | head -1)
              [ -z "$ZIP_FILE" ] && continue

              VERSION=$(unzip -p "$ZIP_FILE" module.prop | grep "^version=" | cut -d'=' -f2-)
              VERSION_CODE=$(unzip -p "$ZIP_FILE" module.prop | grep "^versionCode=" | cut -d'=' -f2-)

              JSON_DIR="${{ github.workspace }}/updateJsons/$ARCH/$TYPE"
              mkdir -p "$JSON_DIR"

              ZIP_FILENAME=$(basename "$ZIP_FILE")
              RELEASE_TAG="build-${{ github.run_number }}"
              ZIP_URL="https://github.com/${{ github.repository }}/releases/download/${RELEASE_TAG}/${ZIP_FILENAME}"

              jq -n \
                --argjson versionCode "$VERSION_CODE" \
                --arg version "$VERSION" \
                --arg zipUrl "$ZIP_URL" \
                --arg changelog "https://raw.githubusercontent.com/${{ github.repository }}/main/changelog.md" \
                '{
                  versionCode: $versionCode,
                  version: $version,
                  zipUrl: $zipUrl,
                  changelog: $changelog
                }' > "$JSON_DIR/updateJson"

            done
          done

      - name: Commit and push all JSON changes
        run: |
          git add changelog.md
          git add updateJsons/*/*/updateJson
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update JSON files for build ${{ github.run_number }}"
            git push origin main
          fi
